### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (6240x4096 and 1x25165824)

### ISSUE THREAD

**Issue by gongye19** [yjang43/lora-multitask#2]
I changed the model along with the target_modules but get the following issue:
the shape of self.weight is bizarre somehow

Traceback (most recent call last):
  File "finetune.py", line 273, in <module>
    finetune(args, evaluate=False)
  File "finetune.py", line 231, in finetune
    loss = model(**batch).loss

***

  File "/home/**/**/**/**/lora-multitask/lora/module.py", line 89, in forward
    result = F.linear(x, self.weight, bias=self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (6240x4096 and 1x25165824)

**Comment by yjang43** [comment]
Could you share the `target_modules.txt` file?

**Comment by gongye19** [comment]
> Could you share the `target_modules.txt` file?

yes, baichuan2 model:

model.layers.0.self_attn.W_pack
model.layers.1.self_attn.W_pack
model.layers.2.self_attn.W_pack
model.layers.3.self_attn.W_pack
model.layers.4.self_attn.W_pack
model.layers.5.self_attn.W_pack
model.layers.6.self_attn.W_pack
model.layers.7.self_attn.W_pack
model.layers.8.self_attn.W_pack
model.layers.9.self_attn.W_pack
model.layers.10.self_attn.W_pack
model.layers.11.self_attn.W_pack
model.layers.12.self_attn.W_pack
model.layers.13.self_attn.W_pack
model.layers.14.self_attn.W_pack
model.layers.15.self_attn.W_pack
model.layers.16.self_attn.W_pack
model.layers.17.self_attn.W_pack
model.layers.18.self_attn.W_pack
model.layers.19.self_attn.W_pack
model.layers.20.self_attn.W_pack
model.layers.21.self_attn.W_pack
model.layers.22.self_attn.W_pack
model.layers.23.self_attn.W_pack
model.layers.24.self_attn.W_pack
model.layers.25.self_attn.W_pack
model.layers.26.self_attn.W_pack
model.layers.27.self_attn.W_pack
model.layers.28.self_attn.W_pack
model.layers.29.self_attn.W_pack
model.layers.30.self_attn.W_pack
model.layers.31.self_attn.W_pack
